page layout
vitali-usik/training-landing-2 pull request #2
Opened 2017-01-22 20:39 UTC by IgorSinyak

HTML + SCSS

2017-01-24 11:58 UTC, vitali-usik requested changes

2017-01-24 11:58 UTC, vitali-usik-work commented on scss/components/mixin.scss
> +
Extra line

2017-01-24 11:58 UTC, vitali-usik-work commented on scss/components/mixin.scss
> +  @if $bg-color == $color-green-blue {
Do we need braces for condition?

2017-01-24 11:58 UTC, vitali-usik-work commented on scss/components/mixin.scss
> +    color: #fff;
Why do you use var for green-blue and not for #fff?

2017-01-24 11:58 UTC, vitali-usik-work commented on scss/components/reset.scss
> +    color:transparent;
Why do you use transparent color?

2017-01-24 11:58 UTC, vitali-usik-work commented on index.html
> +      <div class="container">
duplicated class name

2017-01-24 11:58 UTC, vitali-usik-work commented on index.html
> +              <li>#
Typo?

2017-01-24 11:58 UTC, vitali-usik-work commented on index.html
> +            <div id="right-arrow">></div>
Exta `>`

2017-01-24 11:58 UTC, vitali-usik-work commented on index.html
> +            <li></li>
Is some reason to leave these tags empty?

2017-01-24 12:14 UTC, IgorSinyak commented on scss/components/mixin.scss
> +    color: #fff;
because #fff is easy to write

2017-01-24 12:14 UTC, IgorSinyak commented on scss/components/mixin.scss
> +  @if $bg-color == $color-green-blue {
dont need

2017-01-24 12:18 UTC, IgorSinyak commented on index.html
> +            <li></li>
it`s only container for picture, i can add empty <img> in it with any "alt"

2017-01-24 12:18 UTC, IgorSinyak commented on index.html
> +            <div id="right-arrow">></div>
it`s an arrow symbol ))

2017-01-24 12:18 UTC, IgorSinyak commented on index.html
> +              <li>#
yep

2017-01-24 12:20 UTC, IgorSinyak commented on scss/components/reset.scss
> +    color:transparent;
any other way to hide placeholder on focus?

2017-01-24 12:21 UTC, IgorSinyak commented on index.html
> +      <div class="container">
don`t understand what you mean

2017-01-24 12:32 UTC, vitali-usik-work commented on scss/components/mixin.scss
> +    color: #fff;
Please read about consistency

2017-01-24 12:33 UTC, vitali-usik-work commented on scss/components/reset.scss
> +    color:transparent;
Do you need to hide placeholder on focus? Or when you're starting typing?

2017-01-24 12:33 UTC, vitali-usik-work commented on index.html
> +      <div class="container">
You have another class-name 'container'. A little bit cofusing

2017-01-24 12:34 UTC, vitali-usik-work commented on index.html
> +            <div id="right-arrow">></div>
Please use for it Escape character

2017-01-24 12:35 UTC, vitali-usik-work commented on index.html
> +            <li></li>
But if you needn't such elements - you can remove it

2017-01-24 12:45 UTC, IgorSinyak commented on scss/components/reset.scss
> +    color:transparent;
dont know, i think hide on focus is better

2017-01-24 12:47 UTC, IgorSinyak commented on index.html
> +      <div class="container">
maybe, i`ll check

2017-02-07 16:40 UTC, vitali-usik approved these changes

2017-02-07 16:40 UTC, merged